## Air quality prediction

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')


In [7]:
df= pd.read_csv('Train.csv')
dfy = df['target']
dfx = df.drop('target', axis = 1)
print(dfx.shape)
print(dfy.shape)

(1600, 5)
(1600,)


In [10]:
x_train = dfx.values
y_train = dfy.values

In [11]:
#standardising data
u = np.mean(x_train)
std = np.std(x_train)

x_train = (x_train-u)/std

print(x_train[:5,:])

[[ 0.31139642 -0.92093003 -0.3992678   0.42418404  0.5423883 ]
 [-0.81200658 -0.16864243 -0.75264729 -1.02857829  0.61433283]
 [ 0.25471295  0.15168305 -0.12736142  0.71564009 -0.16678861]
 [ 0.19392955  0.16198536 -0.55840986 -0.10188366 -1.26562851]
 [-1.66430757  0.5593463  -2.76405708 -0.66345183  1.25692511]]


In [12]:
#adding a new column with ones
ones = np.ones((x_train.shape[0],1))
x_train = np.hstack((ones, x_train))
print(x_train.shape)

(1600, 6)


In [50]:
def hypothesis(X, theta):
    return np.dot(X, theta)

def gradient(X,y, theta):
    y_= hypothesis(X,theta)
    grad = np.dot(X.T, (y_-y))
    m = X.shape[0]
    
    return grad/m

def gradient_descent(X, y ,learning_rate = 1, max_iters = 300):
    m = X.shape[1]
    theta = np.zeros((m,))
    
    for i in range(max_iters):
        
        grad = gradient(X,y,theta)
        theta = theta - learning_rate*grad
        
    return theta


    



        

In [51]:
theta = gradient_descent(x_train, y_train)

In [52]:
theta

array([ 1.49138699, 29.84297081, 93.16540718,  8.32556432, 45.01071403,
        2.53283406])

In [53]:
x_test = pd.read_csv('Test.csv')
x_test = x_test.values

ones = np.ones((x_test.shape[0],1))
x_test = np.hstack((ones, x_test))

pred = hypothesis(x_test, theta)
print(pred.shape)

(400,)


In [54]:


df = pd.DataFrame(pred, columns={'target'})
df.to_csv('predictions.csv', index_label = 'Id')